function choice = choosedialogPCA

    d = dialog('Position',[300 300 500 200],'Name','PCA options');
    handles={};
    handles.txt3 = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[10 80 500 90],...
        'String','Select options for the PCA', ...
        'FontSize', 12);

     handles.txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 100 210 40],...
           'String','Select an algorithm (defualt = svd)');
       
     handles.rbut1 = uicontrol('Parent',d,...
           'Style','radiobutton',...
           'Position',[75 90 100 25],...
           'String','svd',...
           'Callback',@rbut1_callback,...
           'Value',1);
     handles.rbut2 = uicontrol('Parent',d,...
           'Style','radiobutton',...
           'Position',[75 70 100 25],...
           'String','eig',...
           'Callback',@rbut2_callback);
     handles.rbut3 = uicontrol('Parent',d,...
           'Style','radiobutton',...
           'Position',[75 50 100 25],...
           'String','als',...
           'Callback',@rbut3_callback);
     handles.txt3 = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[220 0 210 40],...
           'String','als may take few minutes',...
           'Visible', 'off');
       
     handles.btn = uicontrol('Parent',d,...
           'Position',[90 20 70 25],...
           'String','OK',...
           'Callback','delete(gcf)');
     handles.txt2 = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[250 100 210 40],...
           'String','Center the data? (defualt = off)');
       
     handles.rbut4 = uicontrol('Parent',d,...
           'Style','radiobutton',...
           'Position',[305 90 100 25],...
           'String','on',...
           'Callback',@rbut4_callback,...
           'Value',0);
     handles.rbut5 = uicontrol('Parent',d,...
           'Style','radiobutton',...
           'Position',[305 70 100 25],...
           'String','off',...
           'Callback',{@rbut5_callback},...
           'Value',1);
          
     choice = {'svd'; 'off'};
     
     handles.rbut1.Callback ={@rbut1_callback,handles};
     handles.rbut2.Callback ={@rbut2_callback,handles};
     handles.rbut3.Callback ={@rbut3_callback,handles};
     handles.rbut4.Callback ={@rbut4_callback,handles};
     handles.rbut5.Callback ={@rbut5_callback,handles};
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function rbut1_callback(rbut1,callbackdata,handles)
          handles.rbut2.Value=0;
          handles.rbut3.Value=0;
          set( callbackdata.Source.Parent.Children(5), 'Visible', 'off')
          choice{1} = rbut1.String;
       end
       function rbut2_callback(rbut2,callbackdata,handles)
          handles.rbut1.Value=0;
          handles.rbut3.Value=0;
          set( callbackdata.Source.Parent.Children(5), 'Visible', 'off')
          choice{1} = rbut2.String;
       end
       function rbut3_callback(rbut3,callbackdata,handles)
          handles.rbut2.Value=0;
          handles.rbut1.Value=0;
          set( callbackdata.Source.Parent.Children(5), 'Visible', 'on')
          choice{1} = rbut3.String;
       end
       function rbut4_callback(rbut4,callbackdata,handles)
          handles.rbut5.Value=0;
          choice{2} = rbut4.String;
       end
       function rbut5_callback(rbut5,callbackdata,handles)
          handles.rbut4.Value=0;
          choice{2} = rbut5.String;
       end

end