function choice = choosedialogPCA

    d = dialog('Position',[300 300 500 200],'Name','PCA options');
    handles={};
    handles.txt3 = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[10 80 500 90],...
        'String','Select options for the LDA 20-80 test', ...
        'FontSize', 12);
    
    % number of iteration
     handles.txt_iter = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 100 210 40],...
           'String','Select number of iteration (defualt = 10)');
       
     handles.iteration_number = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[240 122 100 20],...
           'String','10',...
           'Callback',@iteration_number_callback);
       
     % precentage of testing
     handles.txt_test = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 75 210 40],...
           'String','percent of testing');
       
     handles.pre_testing = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[240 97 100 20],...
           'String','80',...
           'Callback',@pre_test_callback, ...
           'Enable', 'off');
     
     % precentage of validation
     handles.txt_valid = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 50 210 40],...
           'String','percent of validation');
       
     handles.pre_validation = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[240 72 100 20],...
           'String','20',...
           'Callback',@pre_valid_callback, ...
           'Enable', 'off');
     % run button
     handles.run = uicontrol('Parent',d,...
           'Style','pushbutton',...
           'Position',[380 42 100 60],...
           'String','run',...
           'Callback','delete(gcf)', ...
           'FontSize' , 16);
     % advance button
     handles.advance = uicontrol('Parent',d,...
           'Style','pushbutton',...
           'Position',[380 122 100 20],...
           'String','advance option',...
           'Callback',@advance);
    % note text
      handles.txt_valid = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 20 210 40],...
           'String','note: in each iteration at least   10  percent from each category need to be in the testing group.' ...
           );
      handles.pre_minimum = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[167 45 15 15],...
           'String','10',...
           'Callback',@pre_minimum_callback, ...
           'Visible', 'off');  
       
     choice = {'10'; '80' ;'10'};
     
     handles.iteration_number.Callback ={@iteration_number_callback,handles};
     handles.pre_testing.Callback ={@pre_test_callback,handles};
     handles.pre_validation.Callback ={@pre_valid_callback,handles};
     handles.advance.Callback ={@advance,handles};
     handles.pre_minimum.Callback ={@pre_minimum_callback,handles};
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function iteration_number_callback(rbut1,callbackdata,handles)
          handles.rbut2.Value=0;
          handles.rbut3.Value=0;
          set( callbackdata.Source.Parent.Children(5), 'Visible', 'off')
          choice{1} = rbut1.String;
       end
   
       function pre_test_callback(rbut2,callbackdata,handles)
          choice{2} = handles.pre_testing.String;
          handles.pre_validation.String = num2str(100-str2double( choice{2}));
       end
   
       function advance(rbut3,callbackdata,handles)
          handles.pre_testing.Enable  = 'on';
          handles.pre_minimum.Visible = 'on';
          
       end
   
        function pre_minimum_callback(pre_minimum,callbackdata,handles)
            choice{3} = handles.pre_minimum.String;
        end
   


end